package org.jetbrains.testDiscovery.example;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Foo {
    public String getGreeting() {
        return getClass().getSimpleName();
    }
}
