package org.jetbrains.testDiscovery.example;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class FooTest {
    @Test
    public void testFooGreeting() {
        assertNotNull("Foo should have a greeting", new Foo().getGreeting());
    }
}
